### ISSUE TITLE
Installation Video Langauge

### ISSUE THREAD

**Issue by RobbieJVMW** [bdereims/pks-prep#1]
Translate / Re-Record the installation video guide into English. 

It would be exceptionally helpful if you could deliver an alternative language track for the video in English.

**Comment by bdereims** [comment]
Working on it. Pending!

**Comment by RobbieJVMW** [comment]
😀😀

Sent from my iPhone

On 27 Jun 2018, at 22:15, Brice Dereims <notifications@github.com<mailto:notifications@github.com>> wrote:


Working on it. Pending!
